import { PNG } from "pngjs";
import { describe, expect, test } from "vitest";

import {
  COMMENT_MARKER,
  buildComment,
  buildViewerUrl,
  createThumbnail,
  pruneExpiredReports,
  shouldComment,
  syncComment,
} from "./publish.mjs";

function report(summary) {
  return { files: [], summary, version: 2 };
}

function changedFile(file) {
  return {
    file,
    image: `images/diff/${file}`,
    images: {
      baseline: `images/baseline/${file}`,
      candidate: `images/candidate/${file}`,
      diff: `images/diff/${file}`,
    },
    status: "changed",
  };
}

describe("Frameshift report publishing", () => {
  test("builds a compact summary and candidate thumbnail grid", () => {
    const visualReport = report({
      added: 1,
      changed: 2,
      removed: 1,
      unchanged: 3,
    });
    visualReport.files = [
      changedFile("home__desktop.png"),
      changedFile("home__mobile.png"),
    ];
    const body = buildComment(
      visualReport,
      "https://frameshift.pub/report/?repo=owner%2Frepo&ref=abc",
      "https://raw.githubusercontent.com/owner/repo/abc",
    );

    expect(body).toContain(
      "**4 screenshot changes** — 2 changed · 1 added · 1 removed",
    );
    expect(body).not.toContain("## Frameshift");
    expect(body).toContain("[Review screenshots in Frameshift]");
    expect(body).not.toContain("This report was generated by");
    expect(body).toContain("<table>");
    expect(body).toContain('width="180"');
    expect(body).toContain('height="120"');
    expect(body).toContain('valign="top"');
    expect(body).toContain("Home · Desktop");
    expect(body).toContain(
      "https://raw.githubusercontent.com/owner/repo/abc/thumbnails/home__desktop.png",
    );
    expect(body).not.toContain("images/baseline");
    expect(body).not.toContain("images/diff");
    expect(body).not.toContain("![");
  });

  test("puts thumbnails after the first six in a disclosure", () => {
    const files = Array.from({ length: 8 }, (_, index) =>
      changedFile(`page-${index + 1}__desktop.png`),
    );
    const body = buildComment(
      {
        files,
        summary: { added: 0, changed: 8, removed: 0, unchanged: 0 },
        version: 2,
      },
      "https://frameshift.pub/report/?repo=owner%2Frepo&ref=abc",
      "https://raw.githubusercontent.com/owner/repo/abc",
    );

    expect(body).toContain(
      "<summary>Show 2 more changed screenshots</summary>",
    );
    expect(body.match(/<img /g)).toHaveLength(8);
  });

  test("formats folders and dots as caption sections", () => {
    const body = buildComment(
      {
        files: [
          changedFile("settings/account__mobile.png"),
          changedFile("settings.profile__desktop.png"),
        ],
        summary: { added: 0, changed: 2, removed: 0, unchanged: 0 },
        version: 2,
      },
      "https://frameshift.pub/report/?repo=owner%2Frepo&ref=abc",
      "https://raw.githubusercontent.com/owner/repo/abc",
    );

    expect(body).toContain("Settings · Account · Mobile");
    expect(body).toContain("Settings · Profile · Desktop");
  });

  test("reports no screenshot changes", () => {
    const body = buildComment(
      report({ added: 0, changed: 0, removed: 0, unchanged: 3 }),
      "https://frameshift.pub/",
    );

    expect(body).toContain("**No screenshot changes**");
  });

  test("only comments on matching screenshots when enabled", () => {
    const matching = report({
      added: 0,
      changed: 0,
      removed: 0,
      unchanged: 3,
    });
    const changed = report({
      added: 0,
      changed: 1,
      removed: 0,
      unchanged: 2,
    });

    expect(shouldComment(matching, false)).toBe(false);
    expect(shouldComment(matching, true)).toBe(true);
    expect(shouldComment(changed, false)).toBe(true);
  });

  test("removes an old comment when a rerun has no changes", async () => {
    const requests = [];
    const request = async (_token, endpoint, options = {}) => {
      requests.push({ endpoint, options });
      if (endpoint.includes("comments?")) {
        return [{ body: `${COMMENT_MARKER}\nOld report`, id: 42 }];
      }
      if (options.method === "DELETE") return undefined;
      throw new Error(`Unexpected request: ${endpoint}`);
    };

    await syncComment("token", "owner/repo", 7, undefined, { request });

    expect(requests).toEqual([
      {
        endpoint: "repos/owner/repo/issues/7/comments?per_page=100&page=1",
        options: {},
      },
      {
        endpoint: "repos/owner/repo/issues/comments/42",
        options: { method: "DELETE" },
      },
    ]);
  });

  test("builds the viewer URL from a full Git commit ID", () => {
    expect(
      buildViewerUrl("https://frameshift.pub/", "owner/repo", "abc123"),
    ).toBe("https://frameshift.pub/report/?ref=abc123&repo=owner%2Frepo");
  });

  test("keeps a configured viewer path when building the report URL", () => {
    expect(
      buildViewerUrl("https://example.com/frameshift/", "owner/repo", "abc123"),
    ).toBe(
      "https://example.com/frameshift/report/?ref=abc123&repo=owner%2Frepo",
    );
  });

  test("includes the report expiration in a published viewer URL", () => {
    expect(
      buildViewerUrl(
        "https://frameshift.pub/",
        "owner/repo",
        "abc123",
        1_800_000_000,
      ),
    ).toBe(
      "https://frameshift.pub/report/?expires=1800000000&ref=abc123&repo=owner%2Frepo",
    );
  });

  test("creates a fixed-size top crop", () => {
    const source = new PNG({ height: 120, width: 72 });
    for (let y = 0; y < source.height; y += 1) {
      for (let x = 0; x < source.width; x += 1) {
        const offset = (y * source.width + x) * 4;
        source.data[offset] = y < 48 ? 255 : 0;
        source.data[offset + 1] = 0;
        source.data[offset + 2] = y < 48 ? 0 : 255;
        source.data[offset + 3] = 255;
      }
    }

    const thumbnail = PNG.sync.read(createThumbnail(PNG.sync.write(source)));
    const lastPixel = (thumbnail.width * thumbnail.height - 1) * 4;

    expect(thumbnail.width).toBe(360);
    expect(thumbnail.height).toBe(240);
    expect([...thumbnail.data.subarray(lastPixel, lastPixel + 4)]).toEqual([
      255, 0, 0, 255,
    ]);
  });

  test("removes expired report refs and preserves current reports", async () => {
    const now = Date.UTC(2026, 8, 1);
    const oldTimestamp = Math.floor((now - 31 * 24 * 60 * 60 * 1000) / 1000);
    const currentTimestamp = Math.floor(
      (now - 29 * 24 * 60 * 60 * 1000) / 1000,
    );
    const deleted = [];
    const request = async (_token, endpoint, options = {}) => {
      if (endpoint.endsWith("matching-refs/tags/frameshift-report/")) {
        return [
          {
            object: { sha: "old", type: "commit" },
            ref: `refs/tags/frameshift-report/at-${oldTimestamp}/old/report`,
          },
          {
            object: { sha: "current", type: "commit" },
            ref: `refs/tags/frameshift-report/at-${currentTimestamp}/current/report`,
          },
          {
            object: { sha: "legacy", type: "commit" },
            ref: "refs/tags/frameshift-report/legacy/report",
          },
        ];
      }
      if (endpoint.endsWith("git/commits/legacy")) {
        return { committer: { date: "2026-07-01T00:00:00Z" } };
      }
      if (options.method === "DELETE") {
        deleted.push(endpoint);
        return undefined;
      }
      throw new Error(`Unexpected request: ${endpoint}`);
    };

    const removed = await pruneExpiredReports("token", "owner/repo", 30, {
      now,
      request,
    });

    expect(removed).toBe(2);
    expect(deleted).toEqual([
      `repos/owner/repo/git/refs/tags/frameshift-report/at-${oldTimestamp}/old/report`,
      "repos/owner/repo/git/refs/tags/frameshift-report/legacy/report",
    ]);
  });
});
